# Generated by Django 5.0.7 on 2024-09-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='date_examen',
        ),
    ]
