# Generated by Django 5.0.7 on 2024-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Surveillance', '0001_initial'),
        ('Unite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=100)),
                ('prenom_user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=128)),
                ('cin', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('identifiant', models.CharField(max_length=50)),
                ('roleRes', models.CharField(max_length=50)),
                ('id_surveillance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surveillance.surveillance')),
                ('id_unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unite.unite')),
            ],
        ),
    ]
