# Generated by Django 4.2.5 on 2024-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_appuser_cin_alter_appuser_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cin',
            field=models.CharField(max_length=8),
        ),
    ]
