# Generated by Django 4.2.5 on 2024-09-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_appuser_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cin',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='identifiant',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
