# Generated by Django 4.2.5 on 2024-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_appuser_id_surveillance_appuser_id_unite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='quota',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
