# Generated by Django 4.2.5 on 2024-08-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unite', '0001_initial'),
        ('Surveillance', '0001_initial'),
        ('Users', '0006_alter_appuser_id_surveillance_alter_appuser_id_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id_surveillance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Surveillance.surveillance'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unite.unite'),
        ),
    ]
