# Generated by Django 4.2.5 on 2024-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_appuser_id_surveillance_alter_appuser_id_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='id_surveillance',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='identifiant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='quota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
