# Generated by Django 4.2.5 on 2024-08-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salle', '0003_alter_salle_id_examen'),
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle_examen',
            fields=[
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Salle.salle')),
                ('date_salle', models.DateField()),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen')),
            ],
        ),
    ]
