# Generated by Django 5.0.7 on 2024-09-26 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examen', '0003_examen_nbrclasse'),
        ('Salle', '0004_auto_20240926_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle_examen',
            fields=[
                ('idSE', models.AutoField(primary_key=True, serialize=False)),
                ('date_salle', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen')),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salle.salle')),
            ],
        ),
    ]
