# Generated by Django 5.0.7 on 2024-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('id_contrainte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contrainte', models.CharField(max_length=255)),
                ('type_contrainte', models.CharField(max_length=255)),
                ('date_debut_contrainte', models.DateField()),
                ('date_fin_contrainte', models.DateField()),
                ('status_contrainte', models.CharField(max_length=255)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
