# Generated by Django 4.2.5 on 2024-09-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('id_contrainte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contrainte', models.CharField(max_length=255)),
                ('type_contrainte', models.CharField(max_length=255)),
                ('date_debut_contrainte', models.DateField()),
                ('date_fin_contrainte', models.DateField()),
                ('status_contrainte', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
