# Generated by Django 4.2.5 on 2024-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contrainte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrainte',
            old_name='user_id',
            new_name='user',
        ),
    ]
