# Generated by Django 5.0.7 on 2024-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrainte', '0009_alter_contrainte_date_fin_contrainte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrainte',
            name='date_debut_contrainte',
            field=models.DateTimeField(),
        ),
    ]
