# Generated by Django 5.0.7 on 2024-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_session_date_d_session_date_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_affectation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
