# Generated by Django 5.0.7 on 2024-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_session_current_affectation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exam_count',
            field=models.IntegerField(default=0),
        ),
    ]
