# Generated by Django 5.0.7 on 2024-09-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_session_exam_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exam_count',
        ),
    ]
