# Generated by Django 5.0.7 on 2024-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bloc', '0001_initial'),
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=255)),
                ('capacite', models.IntegerField()),
                ('dispo', models.BooleanField(default=True)),
                ('id_bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloc.bloc')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen')),
            ],
        ),
    ]
