# Generated by Django 5.0.7 on 2024-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id_niveau', models.AutoField(primary_key=True, serialize=False)),
                ('libelleNiv', models.CharField(max_length=255)),
                ('nbclasseNiv', models.IntegerField()),
                ('specialite', models.CharField(max_length=255)),
            ],
        ),
    ]
