# Generated by Django 5.0.7 on 2024-08-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niveau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
