# Generated by Django 5.0.7 on 2024-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=255)),
                ('duree_module', models.IntegerField()),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niveau.niveau')),
            ],
        ),
    ]
