# Generated by Django 4.2.5 on 2024-09-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id_niveau',
        ),
    ]
