# Generated by Django 4.2.5 on 2024-08-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Module', '0001_initial'),
        ('Niveau', '0002_alter_niveau_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_niveau',
            fields=[
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Module.module')),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niveau.niveau')),
            ],
        ),
    ]
