# Generated by Django 5.0.6 on 2024-09-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0001_initial'),
        ('Niveau', '0002_alter_niveau_specialite'),
        ('modniv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modniv',
            fields=[
                ('idmn', models.AutoField(primary_key=True, serialize=False)),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modniv_modules', to='Module.module')),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modniv_niveaux', to='Niveau.niveau')),
            ],
        ),
        migrations.DeleteModel(
            name='Module_niveau',
        ),
    ]
