# Generated by Django 5.0.7 on 2024-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id_surveillance', models.AutoField(primary_key=True, serialize=False)),
                ('date_surveillance', models.DateField()),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salle.salle')),
            ],
        ),
    ]
