# Generated by Django 5.0.7 on 2024-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveillance', '0002_surveillance_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillance',
            name='date_surveillance',
            field=models.DateTimeField(),
        ),
    ]
