# Generated by Django 5.0.7 on 2024-10-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveillance', '0002_surveillance_user'),
        ('Surveillance', '0003_alter_surveillance_date_surveillance'),
    ]

    operations = [
    ]
