# Generated by Django 5.0.7 on 2024-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveillance', '0004_merge_20241002_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillance',
            name='user',
        ),
    ]
