# Generated by Django 4.2.5 on 2024-08-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
        ('Salle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='id_examen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Examen.examen'),
        ),
    ]
