# Generated by Django 4.2.5 on 2024-09-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salle', '0003_alter_salle_id_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='id_examen',
        ),
    ]
