# Generated by Django 5.0.7 on 2024-09-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salle', '0003_alter_salle_id_examen'),
    ]

    operations = [
    ]
