# Generated by Django 5.0.7 on 2024-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.AutoField(primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=255)),
            ],
        ),
    ]
